#!/bin/bash
set -e

SERVICE_NAME=cleaningstatusfilter

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then

    echo "Create virtual environment for application"
    cd "/opt/$SERVICE_NAME"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt 

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/$SERVICE_NAME <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/$SERVICE_NAME
source .venv/bin/activate

python main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/$SERVICE_NAME    

    # link settings file from etc
    cd /opt/$SERVICE_NAME
    ln -sf /etc/$SERVICE_NAME/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start $SERVICE_NAME.service        
    systemctl enable $SERVICE_NAME.service
fi

#DEBHELPER#

exit 0